name = "creator-blueprint"
compatibility_date = "2024-03-20"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "creator-db"
# GANTI database_id DI BAWAH INI DENGAN UUID DARI CLOUDFLARE DASHBOARD ANDA SEBELUM DEPLOY!
database_id = "ba9d3721-9604-46ef-9efc-9a3b1dc92550"
